version: '3'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
          
  db:
    image: 'postgres:14.3'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432
  front:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: front
    depends_on:
      - app
    ports:
      - 80:80