--liquibase formatted sql
--changeset mpernal:01 endDelimiter:GO
CREATE TABLE IF NOT EXISTS BOOK (
    ID  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    TITLE varchar(255) NOT NULL,
    AUTHOR varchar(255) NOT NULL ,
    ISBN varchar(13) NOT NULL unique,
    CONSTRAINT isbn_unique UNIQUE(ISBN)
)
GO

